version: '3'
services:
  flask1:
    build: .
    container_name: flask1
    networks:
      - app-network

  flask2:
    build: .
    container_name: flask2
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask1
      - flask2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
