services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql_db  # Trỏ tới service MySQL
      PMA_PORT: 3306
    ports:
      - "8081:80"  # Truy cập PHPMyAdmin qua cổng 8081
    depends_on:
      - mysql_db
    networks:
      - db_network

volumes:
  mysql_data:

networks:
  db_network:
    driver: bridge