version: '3.8'

services:
  node_app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped