version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_net
    restart: unless-stopped

  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wp_data:/var/www/html
    ports:
      - "8000:80"
    networks:
      - wordpress_net
    restart: unless-stopped

volumes:
  db_data: {}
  wp_data: {}

networks:
  wordpress_net:
    driver: bridge